project_id = "xhziwveaiuhzdoutpgrh"

[functions.create-checkout]
verify_jwt = true

[functions.firecrawl-search]
verify_jwt = true

[functions.firecrawl-scrape]
verify_jwt = true

[functions.firecrawl-map]
verify_jwt = true

[functions.enrich-content]
verify_jwt = true

[functions.enrich-innovation-ecosystem]
verify_jwt = true

[functions.enrich-investors]
verify_jwt = true

[functions.generate-report]
verify_jwt = true

[functions.sync-lemlist]
verify_jwt = true
